/-
Copyright (c) 2026 Gershon Bialer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gershon Bialer
-/
import LeanCompCert.Verified.MulWide

/-!
# Fixed-point `cos` and `sin` terms, and their exact integer brackets

`Verified/LogFixed.lean` computes a fractional logarithm at scale `2^S` and
proves the result correct by an **exact integer bracket** — no `Real`, nothing
rounded, the astronomically large powers occurring only inside a proved
inequality.  This module does the same for the trigonometric series, which is
the remaining primitive an interval evaluator for `riemannZeta` needs:

```
n ^ (-s) = exp (-σ · log n) · (cos (t · log n) - I · sin (t · log n))
```

`logFix` and `expFix` already exist; `cos` and `sin` did not.

## What is computed

An argument `x ∈ [0,1]` is carried as `X = ⌊x · 2^62⌋`, so `X ≤ B62`.  The
individual series terms

```
x ^ (2k) / (2k)!            (cosine)
x ^ (2k+1) / (2k+1)!        (sine)
```

are generated by the standard downward recurrence: multiply by `x` twice, then
divide by the two new factorial factors.  Every operation is a machine
multiply-and-shift (`mulFix`) or a small division, so the whole thing lives in
the proved fragment.

## What is proved

`cosTerm_bracket` and `sinTerm_bracket` say each computed term equals its exact
value to within `2k` units in the last place:

```
cosTerm X k * ((2k)! * B62 ^ (2k))  ≤  X ^ (2k) * B62
X ^ (2k) * B62  ≤  (cosTerm X k + 2k) * ((2k)! * B62 ^ (2k))
```

Divide through by `(2k)! · 2^(62·(2k+1))` and the two lines read
`cosTerm X k / 2^62 ≤ x^(2k)/(2k)! ≤ (cosTerm X k + 2k)/2^62`.  No real number
appears anywhere in the statement.

## Why the *summation* is deliberately not here

The alternating sum `∑ (-1)^k x^(2k)/(2k)!` is not a natural number, and its
relation to `Real.cos` is analysis.  Both belong on the `claude_math` side,
where `Mathlib` exists: `MathExtras.TrigContract.cos_mem_of_partial_sum_bracket`
takes a bracket on the truncated series and returns one on `Real.cos`, and
`MathExtras.TrigTaylor.cos_taylor_bound` supplies the truncation error at
arbitrary order.  Composing those with the per-term bracket below is a triangle
inequality.

That split is the point of the whole design: **the artifact side proves facts
about integers and floor division, and carries no analytic content at all.**

## The error budget

The `2k` ulps are linear rather than exponential because both operations in the
recurrence are contractions: `X ≤ B62` means multiplying by `X/B62` cannot
amplify an existing error, and the factorial divisor is at least `2`.  Each
round therefore adds a bounded constant — the same phenomenon `LogFixed.errB`
records, and the reason a long series stays accurate.
-/

namespace LeanCompCert.Verified.TrigFixed

/-- The fixed-point scale, `2 ^ 62`, matching `LogFixed`. -/
def B62 : Nat := 4611686018427387904

theorem B62_eq : B62 = 2 ^ 62 := by decide

theorem B62_pos : 0 < B62 := by decide

/-- One fixed-point multiplication: `a · b` at scale `B62`, truncated. -/
def mulFix (a b : Nat) : Nat := a * b / B62

/-! ### Two facts about truncating division -/

theorem div_mul_le (a b : Nat) : a / b * b ≤ a := Nat.div_mul_le_self a b

theorem lt_succ_div_mul {a b : Nat} (hb : 0 < b) : a < (a / b + 1) * b := by
  have h := Nat.div_add_mod a b
  have hm : a % b < b := Nat.mod_lt _ hb
  have : (a / b + 1) * b = b * (a / b) + b := by
    simp [Nat.succ_mul, Nat.mul_comm]
  omega

/-! ### The generic recurrence step

Both series use the same round — multiply by `X` twice at scale `B62`, then
divide by the incoming factorial factor `c`.  Stating it once, abstracted over
the accumulated denominator `A` and the exact numerator `R`, means the cosine
and sine inductions differ only in their bookkeeping. -/

/-- Upper half of a round: truncation only ever loses, so an over-estimate of
the exact value is reproduced one level up with no budget paid. -/
theorem step_upper_abs {t X c A R u v w : Nat}
    (h1 : w * c ≤ v) (h2 : v * B62 ≤ u * X) (h3 : u * B62 ≤ t * X)
    (h : t * A ≤ R) :
    w * (A * c * B62 * B62) ≤ R * (X * X) := by
  calc w * (A * c * B62 * B62)
      = (w * c) * (A * B62 * B62) := by
        simp [Nat.mul_comm, Nat.mul_left_comm]
    _ ≤ v * (A * B62 * B62) := Nat.mul_le_mul h1 (Nat.le_refl _)
    _ = (v * B62) * (A * B62) := by
        simp [Nat.mul_comm, Nat.mul_left_comm]
    _ ≤ (u * X) * (A * B62) := Nat.mul_le_mul h2 (Nat.le_refl _)
    _ = (u * B62) * (X * A) := by
        simp [Nat.mul_comm, Nat.mul_left_comm]
    _ ≤ (t * X) * (X * A) := Nat.mul_le_mul h3 (Nat.le_refl _)
    _ = (t * A) * (X * X) := by
        simp [Nat.mul_comm, Nat.mul_left_comm]
    _ ≤ R * (X * X) := Nat.mul_le_mul h (Nat.le_refl _)

theorem step_upper {t X c A R : Nat} (h : t * A ≤ R) :
    (mulFix (mulFix t X) X / c) * (A * c * B62 * B62) ≤ R * (X * X) := by
  unfold mulFix
  exact step_upper_abs (div_mul_le _ c) (div_mul_le _ B62) (div_mul_le _ B62) h

/-- Lower half of a round.  Each of the three truncations loses strictly less
than one unit, and because `X ≤ B62` and `2 ≤ c` neither is amplified, so the
budget grows by the additive constant `2`. -/
theorem step_lower_abs {t X c A R E u v w : Nat} (hX : X ≤ B62) (hc : 2 ≤ c)
    (h1 : v < (w + 1) * c) (h2 : u * X < (v + 1) * B62) (h3 : t * X < (u + 1) * B62)
    (h : R ≤ (t + E) * A) :
    R * (X * X) ≤ (w + (E + 2)) * (A * c * B62 * B62) := by
  have hA : t * X * X ≤ ((u + 1) * B62) * X :=
    Nat.mul_le_mul (Nat.le_of_lt h3) (Nat.le_refl _)
  have hB : (u * X) * B62 ≤ ((v + 1) * B62) * B62 :=
    Nat.mul_le_mul (Nat.le_of_lt h2) (Nat.le_refl _)
  have hC : B62 * X ≤ B62 * B62 := Nat.mul_le_mul (Nat.le_refl _) hX
  have hD : E * (X * X) ≤ E * (B62 * B62) :=
    Nat.mul_le_mul (Nat.le_refl _) (Nat.mul_le_mul hX hX)
  have hassoc : t * X * X = t * (X * X) := Nat.mul_assoc t X X
  have s1 : (u + 1) * B62 * X = u * X * B62 + B62 * X := by
    have d : (u + 1) * B62 * X = u * B62 * X + B62 * X := by simp [Nat.add_mul]
    have a : u * B62 * X = u * X * B62 := by
      simp [Nat.mul_comm, Nat.mul_left_comm]
    rw [d, a]
  have s2 : (v + 1) * B62 * B62 = v * (B62 * B62) + B62 * B62 := by
    have d : (v + 1) * B62 * B62 = v * B62 * B62 + B62 * B62 := by simp [Nat.add_mul]
    have a : v * B62 * B62 = v * (B62 * B62) := Nat.mul_assoc v B62 B62
    rw [d, a]
  have s3 : 2 * (B62 * B62) = B62 * B62 + B62 * B62 := by omega
  have hsum : (t + E) * (X * X) ≤ (v + E + 2) * (B62 * B62) := by
    have hleft : (t + E) * (X * X) = t * (X * X) + E * (X * X) := by simp [Nat.add_mul]
    have hright : (v + E + 2) * (B62 * B62)
        = v * (B62 * B62) + E * (B62 * B62) + 2 * (B62 * B62) := by simp [Nat.add_mul]
    omega
  have hEc : E ≤ E * c := by
    have := Nat.mul_le_mul (Nat.le_refl E) (show 1 ≤ c by omega)
    simpa using this
  have hkey : v + E + 2 ≤ (w + (E + 2)) * c := by
    have e1 : (w + (E + 2)) * c = w * c + (E + 2) * c := by simp [Nat.add_mul]
    have e2 : (w + 1) * c = w * c + c := by simp [Nat.succ_mul]
    have e3 : (E + 2) * c = E * c + 2 * c := by simp [Nat.add_mul]
    omega
  calc R * (X * X)
      ≤ ((t + E) * A) * (X * X) := Nat.mul_le_mul h (Nat.le_refl _)
    _ = ((t + E) * (X * X)) * A := by
        simp [Nat.mul_comm, Nat.mul_left_comm]
    _ ≤ ((v + E + 2) * (B62 * B62)) * A := Nat.mul_le_mul hsum (Nat.le_refl _)
    _ = (v + E + 2) * (A * B62 * B62) := by
        simp [Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    _ ≤ ((w + (E + 2)) * c) * (A * B62 * B62) := Nat.mul_le_mul hkey (Nat.le_refl _)
    _ = (w + (E + 2)) * (A * c * B62 * B62) := by
        simp [Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]

theorem step_lower {t X c A R E : Nat} (hX : X ≤ B62) (hc : 2 ≤ c)
    (h : R ≤ (t + E) * A) :
    R * (X * X) ≤ ((mulFix (mulFix t X) X / c) + (E + 2)) * (A * c * B62 * B62) := by
  have hcpos : 0 < c := by omega
  unfold mulFix
  exact step_lower_abs hX hc (lt_succ_div_mul hcpos) (lt_succ_div_mul B62_pos)
    (lt_succ_div_mul B62_pos) h

/-! ### The cosine terms -/

/-- `fEven k = (2k)!`, built from the two factors each round introduces. -/
def fEven : Nat → Nat
  | 0 => 1
  | k + 1 => fEven k * ((2 * k + 1) * (2 * k + 2))

/-- `cosTerm X k` is `x ^ (2k) / (2k)!` at scale `B62`, where `x = X / B62`. -/
def cosTerm (X : Nat) : Nat → Nat
  | 0 => B62
  | k + 1 => mulFix (mulFix (cosTerm X k) X) X / ((2 * k + 1) * (2 * k + 2))

theorem cosTerm_upper (X : Nat) : ∀ k,
    cosTerm X k * (fEven k * B62 ^ (2 * k)) ≤ X ^ (2 * k) * B62
  | 0 => by simp [cosTerm, fEven]
  | k + 1 => by
    have ih := cosTerm_upper X k
    have hstep := step_upper (t := cosTerm X k) (X := X)
      (c := (2 * k + 1) * (2 * k + 2)) (A := fEven k * B62 ^ (2 * k))
      (R := X ^ (2 * k) * B62) ih
    have hden : fEven (k + 1) * B62 ^ (2 * (k + 1))
        = fEven k * B62 ^ (2 * k) * ((2 * k + 1) * (2 * k + 2)) * B62 * B62 := by
      rw [show 2 * (k + 1) = 2 * k + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [fEven, Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    have hnum : X ^ (2 * (k + 1)) * B62 = X ^ (2 * k) * B62 * (X * X) := by
      rw [show 2 * (k + 1) = 2 * k + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    rw [hden, hnum]
    exact hstep

theorem cosTerm_lower (X : Nat) (hX : X ≤ B62) : ∀ k,
    X ^ (2 * k) * B62 ≤ (cosTerm X k + 2 * k) * (fEven k * B62 ^ (2 * k))
  | 0 => by simp [cosTerm, fEven]
  | k + 1 => by
    have ih := cosTerm_lower X hX k
    have hc : 2 ≤ (2 * k + 1) * (2 * k + 2) := by
      have := Nat.mul_le_mul (show 1 ≤ 2 * k + 1 by omega) (show 2 ≤ 2 * k + 2 by omega)
      omega
    have hstep := step_lower (t := cosTerm X k) (X := X)
      (c := (2 * k + 1) * (2 * k + 2)) (A := fEven k * B62 ^ (2 * k))
      (R := X ^ (2 * k) * B62) (E := 2 * k) hX hc ih
    have hden : fEven (k + 1) * B62 ^ (2 * (k + 1))
        = fEven k * B62 ^ (2 * k) * ((2 * k + 1) * (2 * k + 2)) * B62 * B62 := by
      rw [show 2 * (k + 1) = 2 * k + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [fEven, Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    have hnum : X ^ (2 * (k + 1)) * B62 = X ^ (2 * k) * B62 * (X * X) := by
      rw [show 2 * (k + 1) = 2 * k + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    have hE : 2 * k + 2 = 2 * (k + 1) := by omega
    rw [hden, hnum, ← hE]
    exact hstep

/-- **The `cosFix` bracket.**  `cosTerm X k` is the exact value
`2^62 · x^(2k)/(2k)!` to within `2k` units in the last place, where
`x = X / 2^62 ∈ [0,1]`.  Divide through by `(2k)! · B62 ^ (2k)` to read it. -/
theorem cosTerm_bracket (X : Nat) (hX : X ≤ B62) (k : Nat) :
    cosTerm X k * (fEven k * B62 ^ (2 * k)) ≤ X ^ (2 * k) * B62 ∧
      X ^ (2 * k) * B62 ≤ (cosTerm X k + 2 * k) * (fEven k * B62 ^ (2 * k)) :=
  ⟨cosTerm_upper X k, cosTerm_lower X hX k⟩

/-! ### The sine terms -/

/-- `fOdd k = (2k+1)!`. -/
def fOdd : Nat → Nat
  | 0 => 1
  | k + 1 => fOdd k * ((2 * k + 2) * (2 * k + 3))

/-- `sinTerm X k` is `x ^ (2k+1) / (2k+1)!` at scale `B62`.  The seed is `X`
itself, since `2^62 · x = X`. -/
def sinTerm (X : Nat) : Nat → Nat
  | 0 => X
  | k + 1 => mulFix (mulFix (sinTerm X k) X) X / ((2 * k + 2) * (2 * k + 3))

theorem sinTerm_upper (X : Nat) : ∀ k,
    sinTerm X k * (fOdd k * B62 ^ (2 * k)) ≤ X ^ (2 * k + 1)
  | 0 => by simp [sinTerm, fOdd]
  | k + 1 => by
    have ih := sinTerm_upper X k
    have hstep := step_upper (t := sinTerm X k) (X := X)
      (c := (2 * k + 2) * (2 * k + 3)) (A := fOdd k * B62 ^ (2 * k))
      (R := X ^ (2 * k + 1)) ih
    have hden : fOdd (k + 1) * B62 ^ (2 * (k + 1))
        = fOdd k * B62 ^ (2 * k) * ((2 * k + 2) * (2 * k + 3)) * B62 * B62 := by
      rw [show 2 * (k + 1) = 2 * k + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [fOdd, Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    have hnum : X ^ (2 * (k + 1) + 1) = X ^ (2 * k + 1) * (X * X) := by
      rw [show 2 * (k + 1) + 1 = 2 * k + 1 + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [Nat.mul_assoc]
    rw [hden, hnum]
    exact hstep

theorem sinTerm_lower (X : Nat) (hX : X ≤ B62) : ∀ k,
    X ^ (2 * k + 1) ≤ (sinTerm X k + 2 * k) * (fOdd k * B62 ^ (2 * k))
  | 0 => by simp [sinTerm, fOdd]
  | k + 1 => by
    have ih := sinTerm_lower X hX k
    have hc : 2 ≤ (2 * k + 2) * (2 * k + 3) := by
      have := Nat.mul_le_mul (show 2 ≤ 2 * k + 2 by omega) (show 1 ≤ 2 * k + 3 by omega)
      omega
    have hstep := step_lower (t := sinTerm X k) (X := X)
      (c := (2 * k + 2) * (2 * k + 3)) (A := fOdd k * B62 ^ (2 * k))
      (R := X ^ (2 * k + 1)) (E := 2 * k) hX hc ih
    have hden : fOdd (k + 1) * B62 ^ (2 * (k + 1))
        = fOdd k * B62 ^ (2 * k) * ((2 * k + 2) * (2 * k + 3)) * B62 * B62 := by
      rw [show 2 * (k + 1) = 2 * k + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [fOdd, Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm]
    have hnum : X ^ (2 * (k + 1) + 1) = X ^ (2 * k + 1) * (X * X) := by
      rw [show 2 * (k + 1) + 1 = 2 * k + 1 + 1 + 1 by omega, Nat.pow_succ, Nat.pow_succ]
      simp [Nat.mul_assoc]
    have hE : 2 * k + 2 = 2 * (k + 1) := by omega
    rw [hden, hnum, ← hE]
    exact hstep

/-- **The `sinFix` bracket**, identically shaped: `sinTerm X k` is
`2^62 · x^(2k+1)/(2k+1)!` to within `2k` ulps. -/
theorem sinTerm_bracket (X : Nat) (hX : X ≤ B62) (k : Nat) :
    sinTerm X k * (fOdd k * B62 ^ (2 * k)) ≤ X ^ (2 * k + 1) ∧
      X ^ (2 * k + 1) ≤ (sinTerm X k + 2 * k) * (fOdd k * B62 ^ (2 * k)) :=
  ⟨sinTerm_upper X k, sinTerm_lower X hX k⟩


/-! ### Realizing `mulFix` in the fragment

`mulFix a b = a * b / B62` is the right thing to *state*, but it is not
directly executable: `a * b` is 124 bits and every machine value here is a
`u64`.  `LogFixed.sq62` solves the squaring case with a bespoke half-limb
derivation.  For a general product the carry chain is already done —
`MulWide.hl` returns the exact `(lo, hi)` pair — and the `2⁶²` shift is then
free, because `B64 = 4 · B62` splits with no carry between the two words.

So the trigonometric recurrence needs **no 128-bit intermediate and no
division except by the small factorial factor**, which is what makes it
implementable in the proved fragment. -/

/-- `⌊a·b/2⁶²⌋` from the widening product: the high word contributes four
times, the low word one shift.  `u64`-realizable throughout. -/
def mul62 (a b : Nat) : Nat :=
  let p := MulWide.hl a b
  4 * p.2 + p.1 / B62

theorem mul62_eq (a b : Nat) (ha : a < MulWide.B64) (hb : b < MulWide.B64) :
    mul62 a b = mulFix a b := by
  have h := (MulWide.hl_spec a b ha hb).1
  have hB : MulWide.B64 * (MulWide.hl a b).2 = B62 * (4 * (MulWide.hl a b).2) := by
    simp only [MulWide.B64, B62]
    omega
  show 4 * (MulWide.hl a b).2 + (MulWide.hl a b).1 / B62 = a * b / B62
  rw [← h, hB, Nat.add_mul_div_left _ _ (by decide : 0 < B62)]
  omega

theorem B62_lt_B64 : B62 < MulWide.B64 := by decide

/-! ### The terms stay inside one word

Both operations contract, so every term is bounded by the seed.  This is what
licenses `mul62_eq` at each step. -/

theorem mulFix_le (a : Nat) {X : Nat} (hX : X ≤ B62) : mulFix a X ≤ a := by
  have h1 : a * X ≤ a * B62 := Nat.mul_le_mul (Nat.le_refl a) hX
  have h2 : a * B62 / B62 = a := by
    rw [Nat.mul_div_cancel a (by decide : 0 < B62)]
  calc mulFix a X = a * X / B62 := rfl
    _ ≤ a * B62 / B62 := Nat.div_le_div_right h1
    _ = a := h2

theorem cosTerm_le (X : Nat) (hX : X ≤ B62) : ∀ k, cosTerm X k ≤ B62
  | 0 => Nat.le_refl _
  | k + 1 => by
    have ih := cosTerm_le X hX k
    calc cosTerm X (k + 1)
        ≤ mulFix (mulFix (cosTerm X k) X) X := Nat.div_le_self _ _
      _ ≤ mulFix (cosTerm X k) X := mulFix_le _ hX
      _ ≤ cosTerm X k := mulFix_le _ hX
      _ ≤ B62 := ih

theorem sinTerm_le (X : Nat) (hX : X ≤ B62) : ∀ k, sinTerm X k ≤ B62
  | 0 => hX
  | k + 1 => by
    have ih := sinTerm_le X hX k
    calc sinTerm X (k + 1)
        ≤ mulFix (mulFix (sinTerm X k) X) X := Nat.div_le_self _ _
      _ ≤ mulFix (sinTerm X k) X := mulFix_le _ hX
      _ ≤ sinTerm X k := mulFix_le _ hX
      _ ≤ B62 := ih

/-- **The cosine recurrence, in fragment operations.**  Two widening
multiply-shifts and one division by the incoming factorial factor. -/
theorem cosTerm_succ_mul62 {X : Nat} (hX : X ≤ B62) (k : Nat) :
    cosTerm X (k + 1)
      = mul62 (mul62 (cosTerm X k) X) X / ((2 * k + 1) * (2 * k + 2)) := by
  have hXb : X < MulWide.B64 := Nat.lt_of_le_of_lt hX B62_lt_B64
  have ht : cosTerm X k < MulWide.B64 :=
    Nat.lt_of_le_of_lt (cosTerm_le X hX k) B62_lt_B64
  have h1 : mul62 (cosTerm X k) X = mulFix (cosTerm X k) X := mul62_eq _ _ ht hXb
  have hu : mulFix (cosTerm X k) X < MulWide.B64 :=
    Nat.lt_of_le_of_lt (Nat.le_trans (mulFix_le _ hX) (cosTerm_le X hX k)) B62_lt_B64
  rw [h1, mul62_eq _ _ hu hXb]
  rfl

/-- **The sine recurrence, in fragment operations.** -/
theorem sinTerm_succ_mul62 {X : Nat} (hX : X ≤ B62) (k : Nat) :
    sinTerm X (k + 1)
      = mul62 (mul62 (sinTerm X k) X) X / ((2 * k + 2) * (2 * k + 3)) := by
  have hXb : X < MulWide.B64 := Nat.lt_of_le_of_lt hX B62_lt_B64
  have ht : sinTerm X k < MulWide.B64 :=
    Nat.lt_of_le_of_lt (sinTerm_le X hX k) B62_lt_B64
  have h1 : mul62 (sinTerm X k) X = mulFix (sinTerm X k) X := mul62_eq _ _ ht hXb
  have hu : mulFix (sinTerm X k) X < MulWide.B64 :=
    Nat.lt_of_le_of_lt (Nat.le_trans (mulFix_le _ hX) (sinTerm_le X hX k)) B62_lt_B64
  rw [h1, mul62_eq _ _ hu hXb]
  rfl


/-! ### The terms at least halve

Each round divides by a factorial factor of at least two on top of two
contractions, so the sequence decreases geometrically.  Two consequences, and
both are load-bearing downstream: the partial sums stay inside a single word
(so an emitted accumulator cannot overflow), and the alternating series has
decreasing terms (so consecutive partial sums straddle the value). -/

/-- The halving, at the level of the register file rather than the sequence:
two contractions and a divisor of at least two. -/
theorem step_le_half (t X c : Nat) (hX : X ≤ B62) (hc : 2 ≤ c) :
    mulFix (mulFix t X) X / c ≤ t / 2 :=
  Nat.le_trans (Nat.div_le_div_right
    (Nat.le_trans (mulFix_le _ hX) (mulFix_le _ hX)))
    (Nat.div_le_div_left hc (by decide))

theorem cosTerm_succ_le_half (X : Nat) (hX : X ≤ B62) (k : Nat) :
    cosTerm X (k + 1) ≤ cosTerm X k / 2 := by
  have hc : 2 ≤ (2 * k + 1) * (2 * k + 2) := by
    have h := Nat.mul_le_mul (show 1 ≤ 2 * k + 1 by omega) (show 2 ≤ 2 * k + 2 by omega)
    omega
  have h1 : mulFix (mulFix (cosTerm X k) X) X ≤ cosTerm X k :=
    Nat.le_trans (mulFix_le _ hX) (mulFix_le _ hX)
  show mulFix (mulFix (cosTerm X k) X) X / ((2 * k + 1) * (2 * k + 2))
      ≤ cosTerm X k / 2
  exact Nat.le_trans (Nat.div_le_div_right h1)
    (Nat.div_le_div_left hc (by decide))

theorem sinTerm_succ_le_half (X : Nat) (hX : X ≤ B62) (k : Nat) :
    sinTerm X (k + 1) ≤ sinTerm X k / 2 := by
  have hc : 2 ≤ (2 * k + 2) * (2 * k + 3) := by
    have h := Nat.mul_le_mul (show 2 ≤ 2 * k + 2 by omega) (show 1 ≤ 2 * k + 3 by omega)
    omega
  have h1 : mulFix (mulFix (sinTerm X k) X) X ≤ sinTerm X k :=
    Nat.le_trans (mulFix_le _ hX) (mulFix_le _ hX)
  show mulFix (mulFix (sinTerm X k) X) X / ((2 * k + 2) * (2 * k + 3))
      ≤ sinTerm X k / 2
  exact Nat.le_trans (Nat.div_le_div_right h1)
    (Nat.div_le_div_left hc (by decide))

/-- The running sum of cosine terms. -/
def cosSum (X : Nat) : Nat → Nat
  | 0 => 0
  | n + 1 => cosSum X n + cosTerm X n

/-- **The partial sums fit in one word**, with room to spare: geometric decay
caps them at `2 · B62 = 2^63`, half of `M`.  The `+ 2 * cosTerm X n` is what
makes the induction go through. -/
theorem cosSum_bound (X : Nat) (hX : X ≤ B62) : ∀ n,
    cosSum X n + 2 * cosTerm X n ≤ 2 * B62
  | 0 => by simp [cosSum, cosTerm]
  | n + 1 => by
    have ih := cosSum_bound X hX n
    have hhalf := cosTerm_succ_le_half X hX n
    have h2 : 2 * cosTerm X (n + 1) ≤ 2 * (cosTerm X n / 2) :=
      Nat.mul_le_mul (Nat.le_refl 2) hhalf
    have h3 : 2 * (cosTerm X n / 2) ≤ cosTerm X n := by
      have := Nat.div_add_mod (cosTerm X n) 2
      omega
    show cosSum X n + cosTerm X n + 2 * cosTerm X (n + 1) ≤ 2 * B62
    omega

theorem cosSum_lt (X : Nat) (hX : X ≤ B62) (n : Nat) : cosSum X n < MulWide.B64 := by
  have h := cosSum_bound X hX n
  have hb : 2 * B62 < MulWide.B64 := by decide
  omega


/-- The two parity sums an emitted accumulator maintains. -/
def evenSum (X : Nat) : Nat → Nat
  | 0 => 0
  | n + 1 => evenSum X n + (if n % 2 = 0 then cosTerm X n else 0)

def oddSum (X : Nat) : Nat → Nat
  | 0 => 0
  | n + 1 => oddSum X n + (if n % 2 = 0 then 0 else cosTerm X n)

theorem evenSum_add_oddSum (X : Nat) : ∀ n, evenSum X n + oddSum X n = cosSum X n
  | 0 => rfl
  | n + 1 => by
    have ih := evenSum_add_oddSum X n
    show evenSum X n + (if n % 2 = 0 then cosTerm X n else 0)
      + (oddSum X n + (if n % 2 = 0 then 0 else cosTerm X n))
      = cosSum X n + cosTerm X n
    by_cases h : n % 2 = 0 <;> simp only [h, ite_eq_left, ite_false] <;> omega

theorem evenSum_le_cosSum (X : Nat) (n : Nat) : evenSum X n ≤ cosSum X n := by
  have h := evenSum_add_oddSum X n
  omega

theorem oddSum_le_cosSum (X : Nat) (n : Nat) : oddSum X n ≤ cosSum X n := by
  have h := evenSum_add_oddSum X n
  omega


/-! ### The same accounting for the sine terms -/

def sinSum (X : Nat) : Nat → Nat
  | 0 => 0
  | n + 1 => sinSum X n + sinTerm X n

theorem sinSum_bound (X : Nat) (hX : X ≤ B62) : ∀ n,
    sinSum X n + 2 * sinTerm X n ≤ 2 * B62
  | 0 => by
    show 0 + 2 * X ≤ 2 * B62
    omega
  | n + 1 => by
    have ih := sinSum_bound X hX n
    have hhalf := sinTerm_succ_le_half X hX n
    have h3 : 2 * (sinTerm X n / 2) ≤ sinTerm X n := by
      have := Nat.div_add_mod (sinTerm X n) 2
      omega
    have h2 : 2 * sinTerm X (n + 1) ≤ 2 * (sinTerm X n / 2) :=
      Nat.mul_le_mul (Nat.le_refl 2) hhalf
    show sinSum X n + sinTerm X n + 2 * sinTerm X (n + 1) ≤ 2 * B62
    omega

def sinEvenSum (X : Nat) : Nat → Nat
  | 0 => 0
  | n + 1 => sinEvenSum X n + (if n % 2 = 0 then sinTerm X n else 0)

def sinOddSum (X : Nat) : Nat → Nat
  | 0 => 0
  | n + 1 => sinOddSum X n + (if n % 2 = 0 then 0 else sinTerm X n)

theorem sinEvenSum_add_sinOddSum (X : Nat) : ∀ n,
    sinEvenSum X n + sinOddSum X n = sinSum X n
  | 0 => rfl
  | n + 1 => by
    have ih := sinEvenSum_add_sinOddSum X n
    show sinEvenSum X n + (if n % 2 = 0 then sinTerm X n else 0)
      + (sinOddSum X n + (if n % 2 = 0 then 0 else sinTerm X n))
      = sinSum X n + sinTerm X n
    by_cases h : n % 2 = 0 <;> simp only [h, ite_true, ite_false] <;> omega

#print axioms cosTerm_bracket
#print axioms sinTerm_bracket
#print axioms mul62_eq
#print axioms cosTerm_succ_mul62
#print axioms sinTerm_succ_mul62
#print axioms cosTerm_succ_le_half
#print axioms cosSum_bound

end LeanCompCert.Verified.TrigFixed
